import type { Metadata } from 'next';
import { Roboto } from 'next/font/google';
import './globals.css';
//wrap the session provider
import { SessionProvider } from 'next-auth/react';
import { auth } from '@/auth';
import { Toaster } from '@/components/ui/sonner';

const roboto = Roboto({ subsets: ['latin'], weight: ['100', '300', '400', '500', '700', '900'] });

export const metadata: Metadata = {
	title: 'Krishanro Dough & Co | Dashboard',
	description: 'Generated by create next app',
};

export default async function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	const session = await auth();
	return (
		<SessionProvider session={session}>
			<html lang='en'>
				<body className={roboto.className}>
					<Toaster />
					{children}
				</body>
			</html>
		</SessionProvider>
	);
}
